version: '3.9'

services:
  credit-score-api:
    container_name: credit-score-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - credit-score-service
      
networks:
  credit-score-service: